#include "LSP.h"
#ifdef USE_GMLAN_DEFINES
#ifndef GMLAN_DEFINES_H
#define GMLAN_DEFINES_H

#ifdef USING_GMLAN

// Steering Wheel 
#define SWC_BUTTON_RELEASE 0
#define SWC_VOICE 1
#define SWC_VOLUME_DOWN 2
#define SWC_VOLUME_UP 3
#define SWC_ARROW_UP 4
#define SWC_ARROW_DOWN 5
#define SWC_SOURCE 6
#define SWC_ARROW_RIGHT 7
#define SWC_MAXIMUM_BUTTONS 7 // the highest button value, at least for GM

#define CONNECT_COMMAND 1 // Voice button
#define CONNECT_COMMAND2 2 // Voice button while OnStar on
#define DISCONNECT_COMMAND 3 // hangup button

// Target Sink
#define ENTERTAINMENT 0
#define ANNOUNCEMENT1 1
#define ANNOUNCEMENT2 2
#define REMOTE_PLAYBACK1 3
#define REMOTE_PLAYBACK2 4

#define NO_CHANNEL 0
#define MONO 1
#define STEREO 2
#define MIXED 3
#define SURROUND 4
#define DVD_AUDIO_MODE 5
#define AUDIO_DISC 3
#define SATELLITE_DIGITAL_AUDIO 4
#define VOICE 6
#define DVD_AUDIO 13
#define AUDIO_CD 14

// Infotainment Operation Allowed
#define INFOTAINMENT_ALLOWED 1
#define INFOTAINMENT_NOT_ALLOWED 0

// Audio Source Type
#define AUDIO_SUPERVISOR 0
#define TELEVISION_TUNER 1
#define AUX_DEVICE 8
#define REMOTE_DIGITAL_VIDEO_DISK 12
#define REMOTE_CD_CHANGER 16
#define DIGITAL_AUDIO_BROADCAST 20
#define SATELLITE_DIGITAL_AUDIO_RECEIVER 24
#define PHONE 28

// Audio Master
#define AUDIO_MASTER_ARB_NO_ACTION 0
#define AUDIO_MASTER_ARB_DO_NOT_CONNECT 1
#define AUDIO_MASTER_ARB_CONNECT 2
#define AUDIO_MASTER_ARB_DISCONNECT 3
#define AUDIO_MASTER_ARB_CONNECTION_COMPLETE 4

// Requesting Device Identifier
#define ALL_REQUESTING_DEVICES 0
#define TELEMATICS 1
#define HEAD 2
#define REMOTE_RECEIVER 3
#define REAR_SEAT_ENTERTAINMENT 4
#define AUXILIARY 5
#define ACCOMMODATED_DEVICE_GATEWAY 6
#define CLUSTER 7

// Chime Command 
#define CLOCK 0
#define CLACK 1
#define CLICK 2
#define CLICK_CLACK 3
#define BEEP_750 4
#define BEEP_2000 5
#define GONG_750 6
#define GONG_2000 7
#define HARP 8
#define HIGH_FREQUENCY_BROADBAND 9

// Vehicle Settings
#define ENGLISH 0
#define FRENCH 4
#define SPANISH 5

// Audio Source Status
#define AUDIO_SOURCE_DEVICE_PRESENT 0
#define AUDIO_SOURCE_AUDIO_AVAILABLE 1
#define AUDIO_SOURCE_AUDIO_NOT_AVAILABLE 2
#define AUDIO_SOURCE_RESERVED 3
#define AUDIO_SOURCE_PRODUCING_SILENCE 4
#define AUDIO_SOURCE_PRODUCING_AUDIO 5

//Power Mode
#define POWER_MODE_OFF 0
#define POWER_MODE_ACCESSORY 1
#define POWER_MODE_IGNITION 2
#define POWER_MODE_CRANK 3
#define POWER_MODE_MASK 3

// Audio Master Amplifier Mute Command
#define AUDIO_MASTER_AMP_MUTE_COMMAND_UNMUTE 0
#define AUDIO_MASTER_AMP_MUTE_COMMAND_MUTE 1
#define ENTERTAINMENT 0
#define ANNOUNCEMENT1 1
#define ANNOIUNCEMENT2 2
#define REMOTE_PLAYBACK1 3
#define REMOTE_PLAYBACK2 4


// Audio Master Amplifier Settings Control
#define AUDIO_MASTER_AMP_SETTINGS_CONTROL_VOLUME 0
#define AUDIO_MASTER_AMP_SETTINGS_CONTROL_FADE 1
#define AUDIO_MASTER_AMP_SETTINGS_CONTROL_BALANCE 2
#define AUDIO_MASTER_AMP_SETTINGS_CONTROL_BASS 3
#define AUDIO_MASTER_AMP_SETTINGS_CONTROL_MIDRANGE 4
#define AUDIO_MASTER_AMP_SETTINGS_CONTROL_TREBLE 5
#define AUDIO_MASTER_AMP_SETTINGS_CONTROL_MULTI_CHANNEL 6
#define AUDIO_MASTER_AMP_SETTINGS_CONTROL_DIGITAL_SIGNAL_PROCESSING 7
#define AUDIO_MASTER_AMP_SETTINGS_CONTROL_VEHICLE_NOISE_COMPENSATION 8
#define AUDIO_MASTER_AMP_SETTINGS_CONTROL_SPEED_COMPENSATED_VOLUME 9

// AudioMasterAmplifierSettings?
#define SETTING_TIME_0 0
#define SETTING_TIME_25 25
#define MIDDLE_SETTING 126
#define VOLUME_SETTING_98 250
#define VOLUME_SETTING_90 229
#define VOLUME_SETTING_85 216
#define VOLUME_SETTING_80 204
#define VOLUME_SETTING_75 191

// Audio Master Amplifier Command
#define AMPLIFIER_MUTE 0
#define AMPLIFIER_UNMUTE 1
#define REAR_SEAT_AUDIO_ENABLE 2
#define REAR_SEAT_AUDIO_DISABLE 3
#define AM_AUDIO_TYPE 4
#define FM_AUDIO_TYPE 5
#define VOICE_AUDIO_TYPE 6
#define DIGITAL_STEREO_AUDIO_TYPE 7
#define ANALOG_STEREO_AUDIO_TYPE 8
#define DIGITAL_SIGNAL_PROCESSOR_SETTING_1 17
#define DIGITAL_SIGNAL_PROCESSOR_SETTING_2 18
#define DIGITAL_SIGNAL_PROCESSOR_SETTING_3 19
#define DIGITAL_SIGNAL_PROCESSOR_SETTING_4 20
#define DIGITAL_SIGNAL_PROCESSOR_SETTING_5 21
#define DIGITAL_SIGNAL_PROCESSOR_SETTING_6 22
#define DIGITAL_SIGNAL_PROCESSOR_SETTING_7 23

// Audio Master Amplifier Control
#define AUDIO_MASTER_AMPLIFIER_CONTROL_DISCONNECT 0
#define AUDIO_MASTER_AMPLIFIER_CONTROL_CONNECT 1
/* these are already defined*/
//#define NO_CHANNEL 0
//#define MONO 1
//#define STEREO 2
//#define MIXED 3
//#define SURROUND 4
//#define DVD_AUDIO_MODE 5


#define NO_TYPE 0
#define AM_LONG_WAVE 1
#define FM 2
#define AUDIO_DISC 3
#define SATELLITE_DIGITAL_AUDIO 4
#define TELEVISION 5
#define VOICE 6
#define CASSETTE_TAPE 7
#define WEATHER 8
#define NAVIGATION_PROMPTS 9
#define FRONT_AUXILIARY_INPUT 10
#define REAR_AUXILIARY_INPUT 11
#define DVD_VIDEO 12
#define DVD_AUDIO 13
#define AUDIO_CD 14
#define COMPRESSED_AUDIO 15

/* Requesting Device Identifier */
#define ALL_REQUESTING_DEVICES 0
#define TELEMATICS 1
#define HEAD 2
#define REMOTE_RECEIVER 3
#define REAR_SEAT_ENTERTAINMENT 4
#define AUXILIARY 5
#define ACCOMMODATED_DEVICE_GATEWAY 6
#define CLUSTER 7

/* Target Display Device Identifier and ArbTextDisplayLineAttributes */
#define INFOTAINMENT_DISPLAY 1
#define HEADUP_DISPLAY 2
#define CLUSTER_DISPLAY 3
#define COCKPIT_DISPLAY 4
#define REAR_SEAT_DISPLAY 5
#define AUXILIARY_DISPLAY 6
#define NAVIGATION_DISPLAY 7

/* Target Display Device Session Mode */
#define NONE 0
#define STATIC_ARBITRARY_TEXT_MODE 1
#define STATIC_ARBITRARY_TEXT_MODE_WITH_ICON 2
#define NAVIGATION_MODE 3
#define SCROLLING_ARBITRARY_TEXT_MODE 4
#define SCROLLING_ARBITRARY_TEXT_MODE_WITH_ICON 5
#define SCROLLING_ARBITRARY_TEXT_MODE_TITLE 6
#define SCROLLING_ARBITRARY_TEXT_MODE_WITH_ICON_TITLE 7
#define DIALOG_MODE 8
#define DOWNLOAD_ICON_MODE 9
#define DOWNLOAD_NAVIGATION_ICON_MODE 10
#define DOWNLOAD_ARBITRARY_TEXT_DATA 11

/* Session Function Code */
//#define NONE 0 // already defined
#define EMERGENCY 1
#define URGENT_TURN_BY_TURN_PROMPT 2
#define URGENT_SEVICE_APLLICATION_PROMPT 3
#define USER_DIALOG 4
#define USER_SCROLL 5
#define NON_URGENT_TURN_BY_TURN_PROMPT 6
#define NON_URGENT_SERVICE_APPL_PROMPT 7
#define PHONE_INFORMATION 8
#define PHONE_TIMER 9
#define DIGITAL_BROADCAST_LABEL 10
#define SONG_TITLE 11
#define SONG_ARTIST 12
#define AVAILABLE_PROGRAMT_YPE 13
#define PROGRAM_NAME 14
#define CURRENT_PROGRAM_NAME 15
#define REMOTE_RECEIVER_INFO_DATA_TRANSFER 16
#define MUSIC_FILE_INFO_DATA_TRANSFER 17
#define ONSTAR_DESTINATION_DOWNLOAD 18

/* Character Set */
#define BASE_CHARACTER_SET 1
#define UNICODE 2
#define BLOCK_UNICODE_IDEOGRAPH 3
/* Font */
#define SMALL 1
#define LARGE 2
#define DUAL 3
/* Horizontal Justify */
#define LEFT 1
#define RIGHT 2
#define CENTER 3

/* Message Operation Status */
#define DISPLAY_TURNED_OFF_UNAVAILABLE 0
#define DATA_TRANSFER_GRANTED 1
#define DATA_TRANSFER_NOT_GRANTED 2
#define DISPLAY_AVAILABLE 3
#define INVALID_DATA_LENGTH 4
#define DATA_TRANSFER_TIMEDOUT 5
#define INVALID_DATA 6
#define REQUESTED_DISPLAY_NOW_ON 7
#define REQUESTED_DISPLAY_NOW_OFF 8
#define REQUESTED_DISPLAY_CANCELED 9
#define REQEUESTED_DISPLAY_CANCELED_USER_ACTION 10
#define ICON_TRANSFER_SUCCESSFUL 11
#define DELETED_ICON_TAG_NUMBER 12
#define RECONFIGURABLE_MENU_ENTRY_REQUESTED 13

/*RemoteReciverStatus*/
//
//Station Preset number
#define NOT_A_PRESET 0
//Current station service
#define GENERAL_SUBSCRIPTION 1
//Current Station Quality
#define INSUFFICIANT_SIGNAL 0
#define SUFFICIANT_SIGNAL 1
//Remote Receiver DataType
#define NO_UPDATE 0
#define AUDIO 1
#define DATA 2
#define VIDEO 3
#define UNKNOWN 7
//Remote Receiver Command Status
#define VALID_COMMAND 1
#define NOT_SUPPORTED 2
#define OUT_OF_RANGE 3
//Remote Receiver Scanning Status
#define NO_ACTION 0
#define SCANNING_BY_STATION 1
#define SCANNING_BY_PROGRAM_TYPE 2
#define SCANNING_BY_PRESETS 3
//Interrup Status
#define ENABLED 1
#define COMING 2
#define ENDED 3
#define SUPPORTED 4
//Tuning Status
#define TUNED 0
#define TUNING 1
//Seeking Status
#define SEEKING_BY_STATION 1
#define SEEKING_BY_PROGRAM_TYPE 2
#define SEEKING_BY_PRESETS 3
//Type
#define SAT_DIGITAL_AUDIO_RECEIVER_SYSTEM 0
#define SAT_DIGITAL_AUDIO_BROADCAST 1
#define REMOTE_AM_FM_TUNER 2
//Service Provider
#define NOT_AVAILABLE 0
#define XM_COMPANY 1
#define SIRIUS 2
/*end RemoteReciverStatus*/

/* AdvanceRemoteReceiverControl */
//#define NO_ACTION 0
#define STATION 1
#define STATION_DELTA 2
#define PROGRAM_TYPE 3
#define PROGRAM_TYPE_DELTA 4
#define RECALL_PRESET_NUMBER 5
#define SET_PRESET 6
#define SEEK_UP 7
#define SEEK_DOWN 8
#define SEEK_PROGRAM_TYPE_UP 9
#define SEEK_PROGRAM_TYPE_DOWN 10
#define SEEK_PRESET_UP 11
#define SEEK_PRESET_DOWN 12
#define SCAN_UP 13
#define SCAN_DOWN 14
#define SCAN_PRESET_UP 15
#define SCAN_PRESET_DOWN 16
#define SCAN_PROGRAM_TYPE_UP 17
#define SCAN_PROGRAM_TYPE_DOWN 18
#define STATION_DELTA_WITHIN_PROGRAM_TYPE 19
#define AUTO_STORE 20
#define AUDIO_PROGRAM_SERVICE_IDENTIFIER 21
#define LIST_REQUEST 22

/* end AdvanceRemoteReceiverControl */

// Mirror Movement Request
#define NO_MIRROR_SELECTED 0
#define LEFT_OUTSIDE_MIRROR_SELECTED 1
#define RIGHT_OUTSIDE_MIRROR_SELECTED 2
#define INSIDE_MIRROR_SELECTED 3

#define NO_ACTIVATION 0
#define MIRROR_UP 1
#define MIRROR_DOWN 2
#define MIRROR_LEFT 1
#define MIRROR_RIGHT 2
#define MIRROR_TILT 1
#define MIRROR_UNTILT 2
#define MIRROR_EXTEND 1
#define MIRROR_RETRACT 2
#define MIRROR_FOLD 1
#define MIRROR_UNFOLD 2
#define MIRROR_ENGAGE 3
/* end Mirror Movement Request */

#endif // USING_GMLAN

#ifdef USING_GMLAN_V2

//Power Mode
#define POWER_MODE_OFF 0
#define POWER_MODE_ACCESSORY 1
#define POWER_MODE_IGNITION 2
#define POWER_MODE_CRANK 3
#define POWER_MODE_MASK 3

// Chime Command 
#define CLOCK 0
#define CLACK 1
#define CLICK 2
#define CLICK_CLACK 3
#define BEEP_750 4
#define BEEP_2000 5
#define GONG_750 6
#define GONG_2000 7
#define HARP 8
#define HIGH_FREQUENCY_BROADBAND 9

#endif // USING_GMLAN_V2



#endif // GMLAN_DEFINES_H
#endif // USE_GMLAN_DEFINES
