#include "LSP.h"
#ifdef USE_MERCEDES_CAN_ID
#ifndef MERCEDES_CAN_ID
#define MERCEDES_CAN_ID


#define POWER_MODE_ID 0x001
#define GEAR_INFORMATION_ID 0x388
#define TURN_SIGNAL_HIGH_BEAMS_ID 0x45
#define SWC_ID 0x3F6
#define PARKING_BRAKE_ID 0x006
#define PARKING_LIGHT_ID 0x04B
#define DRIVER_DOOR_ID 0x002
#define DIMMER_ID 0x015
#define VSS_ID 0x19F

#endif// MERCEDES_CAN_ID
#endif // USE_MERCEDES_CAN_ID

